apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-api
  template:
    metadata:
      labels:
        app: store-api
    spec:
      serviceAccountName: store-api-oidc
      containers:
        - name: store-api
          image: your-registry/store-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: your-database-url
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
