---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    aws:  
      service: SecretsManager 
      region: ap-south-1

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: postgresql-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: store-api-db-secrets
      property: POSTGRES_USER
  - secretKey: POSTGRES_DB
    remoteRef:
      key: store-api-db-secrets
      property: POSTGRES_DB
  - secretKey: POSTGRES_HOST
    remoteRef:
      key: store-api-db-secrets
      property: POSTGRES_HOST
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: store-api-db-secrets
      property: POSTGRES_PASSWORD