apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: dGVzNkFlNjhk
  POSTGRES_DB: cGxpdm8=
  POSTGRES_USER: cGxpdm8=
  POSTGRES_HOST: cG9zdGdyZXNxbC0wLnBvc3RncmVzcWwtc3ZjLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw=
