serviceAccount:
  create: true
  annotations: 
    eks.amazonaws.com/role-arn: ${ROLE_ARN}
  name: ${SERVICE_ACCOUNT}

config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level INFO
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            ${ES_CLUSTER_ENDPOINT}
        Port            443
        TLS             On
        AWS_Auth        On
        AWS_Region      ${AWS_REGION}
        Retry_Limit     6
        Logstash_Format On
        Logstash_DateFormat %Y%m%d
        Logstash_Prefix application-logs
        Trace_Error     On
        Replace_Dots    On

    [OUTPUT]
        Name            es
        Match           host.*
        Host            ${ES_CLUSTER_ENDPOINT}
        Port            443
        TLS             On
        AWS_Auth        On
        AWS_Region      ${AWS_REGION}
        Retry_Limit     6
        Logstash_Format On
        Logstash_DateFormat %Y%m%d
        Logstash_Prefix kubernetes-system-services
        Trace_Error     On
        Replace_Dots    On
